name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses
      - name: Force Gradle 8.6 wrapper
        run: ./gradlew wrapper --gradle-version 8.6 --distribution-type bin

      - name: Generate local.properties (SDK path)
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
